### ISSUE TITLE
Not Working on action bar 1 but all others

### ISSUE THREAD

**Issue by Frooooop** [Xruptor/RightClickSelfCast#4]
Hey, 
I really like the Addon, but i have the following issue: i can´t rightclick spells to cast on myself when they are on Actionbar 1... Rightclick is working great on all other actionbars, but not on bar 1. I´ve tried to disable all other Addons and its still not working, i´m also not using Elvui or any other Addons like that

**Comment by Xruptor** [comment]
This is extremely odd because I'm currently playing with the addon enabled and no other actionbar addons installed.  (This includes no bartender).  I'm using the basic generic Blizzard Action Bars and it works fine for me on Action Bar 1.  I've tested it on several characters.  It's easier to test with healers as you can just right click to heal yourself.  Are you sure you don't have anything else installed or possibly an option enabled in the settings?

**Comment by Frooooop** [comment]
as i said, i even tried it with all other addons disabled. But good news is, i tried deleting and reinstalling it and now its working! Must have been an issue during installation via curseforge or something like that, idk.

**Comment by Xruptor** [comment]
> 

Oh haha yeah that happens sometimes.  Perhaps there was an error generated and you didn't see it because it was hidden.  That happens sometimes and locks out GUI stuff.  :)  I'm glad it worked out.  You can always try BugSack in the future for situations like these!  It's does wonders for finding buggy stuff.

https://www.curseforge.com/wow/addons/bugsack
Requires this addon:  https://www.curseforge.com/wow/addons/bug-grabber
