### ISSUE TITLE
WoW Classic: no working with addon MoveAny

### ISSUE THREAD

**Issue by AzucarSalado** [Xruptor/RightClickSelfCast#5]
Not woking with the aaddon WorkAny, I had no error in BugSack, so I started disabling all addons and  enabling one by one. I arrived to these conclussions:

1.- With all addons dissabled, it still was not working. It happened that I had one key assigned in "Interface options" > "Self Cast Key". I changed to "None" and then it worked in all bars. I beleive that by default WoW comes with one key assigned.
2.- When I enabled, "MoveAny". Stopped working partially:
2.1.- It still works with what MoveAny calls Actionbars 1 + 5 +6. But,
2.2.- It does not work with the rest of the bars: bars  nº 3 (right bar), nº 4 (left bar), 7, 8, 9.

I will search for help in WorkAny too.

Cheers.-

**Comment by Xruptor** [comment]
I don't have a current subscription so I'll have to have another friend test it.  It should work though as the addon only sets the right click function of the actionbar slot.  Unless you are using a custom actionbar addon like Bartender, it should technically work.

**Comment by Xruptor** [comment]
Okay I was able to move everything around and rightclick on the Classic PTR server (since I have no access to live with no subscription).  I'll try a few other things but I couldn't seem to replicate this.  I still was able to right click and self cast.  Perhaps its region specific?  Are you playing on the enUS client and in the USA?
